
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-e2e-tests","number":89,"title":"tr - ucsb dining commons menu item e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/89"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-integration-tests","number":88,"title":"tr - add integration test for UCSBDiningCommonsMenuItem Controller endpoints","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/88"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-copyPlaceholders-helpRequest","number":87,"title":"placeholders for HelpRequest pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/87"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"article-form-component","number":85,"title":"Article form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/85"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-create_fixtures_MenuItemReview","number":82,"title":"js - created fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/82"}]
