
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-IndexPage","number":80,"title":"tr - ucsb dining commons menu item index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/80"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-Edit-Page","number":79,"title":"tr - ucsb dining commons menu item edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/79"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-create-page","number":78,"title":"tr - ucsb dining commons menu item create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/78"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-add-fixtures","number":70,"title":"added recommendationrequestfixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/70"}]
