
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"sl-articles-integration-tests","number":123,"title":"sl - add inegration tests for Articles controller endpoints","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/123"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-Placeholder","number":120,"title":"js - menu item review copy placeholder","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/120"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-table","number":118,"title":"js-menu item review table","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/118"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-form","number":116,"title":"js-add form for menu item review","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/116"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-edit-page","number":113,"title":"ws - added edit page and tests for recommendation request","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/113"}]
