
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-edit-page","number":113,"title":"ws - added edit page and tests for recommendation request","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/113"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-create-page","number":110,"title":"ws - create page + tests for recommendation request","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/110"},{"author":{"id":"U_kgDOB2-2PA","is_bot":false,"login":"Sauld04","name":"Saul Diaz "},"headRefName":"sd-UCSBOrganization-e2e-tests","number":108,"title":"sd - ucsb organization e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/108"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-UCSBDiningCommonsMenuItem-e2e-tests","number":89,"title":"tr - ucsb dining commons menu item e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/89"}]
