
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-not-real","number":130,"title":"js - menu item review index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/130"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-index-MenuItemReview-page","number":129,"title":"js-index menu item review page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/129"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-create-MenuItemReview-page","number":128,"title":"js - create menu item review page","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/128"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-Placeholder","number":120,"title":"js - menu item review copy placeholder","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/120"}]
