
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-11
owner: ucsb-cs156-s25
repo_name: team02-s25-11
pull_requests: [{"author":{"id":"U_kgDOB2-2PA","is_bot":false,"login":"Sauld04","name":"Saul Diaz "},"headRefName":"sd-copy-backend-for-UCSBOrganizations","number":66,"title":"sd - copy backend CRUD operations from team01 for the UCSBOrgs table","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/66"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"sl-copy-backend-for-articles","number":65,"title":"sl - copy backend CRUD operations from team01 for articles table","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/65"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-HelpRequest-backend","number":62,"title":"copied HelpRequest files","url":"https://github.com/ucsb-cs156-s25/team02-s25-11/pull/62"}]
